// questions-answers.js

export const qaPairs = [
    // General Knowledge
    { question: "Как называется самая большая планета в Солнечной системе?", answer: "The largest planet in the Solar System is Jupiter." },
    { question: "Кто написал 'Гарри Поттера'?", answer: "Harry Potter was written by J.K. Rowling." },
    { question: "Какой океан самый большой?", answer: "The Pacific Ocean is the largest ocean." },
    { question: "Сколько часов в сутках?", answer: "There are 24 hours in a day." },
    { question: "Какое самое высокое здание в мире?", answer: "The tallest building in the world is the Burj Khalifa." },
    { question: "Сколько континентов на Земле?", answer: "There are seven continents on Earth." },
    { question: "Что такое гравитация?", answer: "Gravity is a force that attracts objects toward one another." },
    { question: "Как называется столица Франции?", answer: "The capital of France is Paris." },
    { question: "Кто был первым человеком на Луне?", answer: "The first person on the Moon was Neil Armstrong." },
    { question: "Сколько планет в Солнечной системе?", answer: "There are eight planets in the Solar System." },
    { question: "Какой газ мы вдыхаем?", answer: "We breathe in oxygen." },
    { question: "Какое самое быстрое наземное животное?", answer: "The cheetah is the fastest land animal." },
    { question: "Какое самое большое животное на Земле?", answer: "The blue whale is the largest animal on Earth." },
    { question: "Сколько сторон у квадрата?", answer: "A square has four sides." },
    { question: "Какой элемент символизируется буквой 'O'?", answer: "The element represented by 'O' is oxygen." },
    { question: "Что такое фотосинтез?", answer: "Photosynthesis is a process plants use to make food." },
    { question: "Сколько месяцев в году?", answer: "There are twelve months in a year." },
    { question: "Кто написал 'Иллиаду'?", answer: "The Iliad was written by Homer." },
    { question: "Какой самый большой штат в США?", answer: "The largest state in the USA is Alaska." },
    { question: "Сколько костей в теле человека?", answer: "There are 206 bones in the human body." },
    { question: "Какой фрукт известен высоким содержанием калия?", answer: "Bananas are known for their high potassium content." },
    { question: "Сколько секунд в минуте?", answer: "There are 60 seconds in a minute." },
    { question: "Кто создал теорию относительности?", answer: "The theory of relativity was developed by Albert Einstein." },
    { question: "Как называется столица Японии?", answer: "The capital of Japan is Tokyo." },
    { question: "Сколько градусов в полном круге?", answer: "There are 360 degrees in a full circle." },
    { question: "Кто написал 'Анну Каренину'?", answer: "Anna Karenina was written by Leo Tolstoy." },
    { question: "Какой язык является самым распространённым?", answer: "Mandarin Chinese is the most spoken language worldwide." },
    { question: "Кто был первым президентом США?", answer: "The first president of the USA was George Washington." },
    { question: "Какой металл известен как самый тяжёлый?", answer: "Osmium is known as the heaviest metal." },
    { question: "Какая страна имеет самую большую площадь?", answer: "Russia has the largest land area." },
    { question: "Кто написал 'Ромео и Джульетта'?", answer: "Romeo and Juliet was written by William Shakespeare." },
    { question: "Как называется самая маленькая кость в теле человека?", answer: "The smallest bone in the human body is the stapes." },
    { question: "Какой газ используется в воздушных шарах?", answer: "Helium is used in balloons." },
    { question: "Как называется столица Италии?", answer: "The capital of Italy is Rome." },
    { question: "Какая планета известна своими кольцами?", answer: "Saturn is known for its rings." },
    { question: "Кто написал 'Одиссею'?", answer: "The Odyssey was written by Homer." },
    { question: "Как называется самая большая пустыня?", answer: "The largest desert is the Sahara." },
    { question: "Какая страна изобрела пасту?", answer: "Italy is credited with inventing pasta." },
    { question: "Какая страна родина пиццы?", answer: "Italy is the birthplace of pizza." },
    { question: "Сколько букв в английском алфавите?", answer: "There are 26 letters in the English alphabet." },
    { question: "Как называется корень квадратный из 64?", answer: "The square root of 64 is 8." },
    { question: "Какой самый высокий водопад в мире?", answer: "The tallest waterfall in the world is Angel Falls." },
    { question: "Какой день после вторника?", answer: "The day after Tuesday is Wednesday." },
    { question: "Как называется столица Великобритании?", answer: "The capital of the United Kingdom is London." },
    { question: "Какой химический символ для золота?", answer: "The symbol for gold is Au." },
    { question: "Как называется самая длинная река?", answer: "The Nile is considered the longest river." },
    { question: "Какой фрукт на первом месте по потреблению в мире?", answer: "The banana is one of the most consumed fruits." },
    { question: "Сколько сторон у треугольника?", answer: "A triangle has three sides." },
    { question: "Сколько полюсов у магнита?", answer: "A magnet has two poles." },
    { question: "Какой металл плавится при самой низкой температуре?", answer: "Mercury has the lowest melting point." },
    { question: "Какой орган человеческого тела качает кровь?", answer: "The heart pumps blood throughout the body." },
    { question: "Какой самый быстрый способ передвижения?", answer: "Flying is the fastest mode of travel." },
    { question: "Какая самая большая страна по численности населения?", answer: "China has the largest population." },
    { question: "Какой элемент символизируется буквой 'H'?", answer: "The element symbolized by 'H' is hydrogen." },
    { question: "Какой самый лёгкий элемент?", answer: "The lightest element is hydrogen." },
    { question: "Какой океан находится между Африкой и Австралией?", answer: "The Indian Ocean is located between Africa and Australia." },
    { question: "Какой город называют 'Большим яблоком'?", answer: "New York City is known as 'The Big Apple'." },
    { question: "Какой самый высокий вулкан в мире?", answer: "Ojos del Salado is the highest volcano in the world." },
    { question: "Какой фрукт называют 'королём фруктов'?", answer: "The mango is often called the 'king of fruits'." },
    { question: "Какое животное символ мудрости?", answer: "The owl is a symbol of wisdom." },
    { question: "Какая страна известна как 'страна восходящего солнца'?", answer: "Japan is known as the 'Land of the Rising Sun'." },
    { question: "Как называется планета, наиболее похожая на Землю?", answer: "Mars is considered the planet most similar to Earth." },
    { question: "Какая самая маленькая страна в мире?", answer: "The smallest country in the world is Vatican City." },
    { question: "Какой газ необходим для дыхания?", answer: "Oxygen is essential for breathing." },
    { question: "Сколько дней в високосном году?", answer: "There are 366 days in a leap year." },
    { question: "Сколько дней в обычном году?", answer: "There are 365 days in a common year." },
    { question: "Какой химический символ для воды?", answer: "The chemical symbol for water is H2O." },
    { question: "Какая планета самая горячая?", answer: "Venus is the hottest planet." },
    { question: "Кто написал 'Гамлета'?", answer: "Hamlet was written by William Shakespeare." },
    { question: "Какой газ обнаружил Джозеф Пристли?", answer: "Joseph Priestley is credited with discovering oxygen." },
    { question: "Какая страна использует фунт как валюту?", answer: "The United Kingdom uses the pound as currency." },
    { question: "Какой самый маленький океан?", answer: "The Arctic Ocean is the smallest ocean." },
    { question: "Кто был первым человеком в космосе?", answer: "The first person in space was Yuri Gagarin." },
    { question: "Сколько планет в Солнечной системе?", answer: "There are eight planets in the Solar System." },
    { question: "Какая страна находится между Россией и Индией?", answer: "China lies between Russia and India." },
    { question: "Какая планета известна как 'красная планета'?", answer: "Mars is known as the 'Red Planet'." },
    { question: "Какая планета имеет кольца?", answer: "Saturn is famous for its rings." },
    { question: "Какой язык самый распространенный?", answer: "The most spoken language worldwide is Mandarin." },
    { question: "Как называется инструмент для измерения температуры?", answer: "A thermometer measures temperature." },
    { question: "Сколько нот в музыке?", answer: "There are seven basic musical notes." },
    { question: "Какой город является столицей Канады?", answer: "The capital of Canada is Ottawa." },
    { question: "Кто написал 'Алису в Стране чудес'?", answer: "Alice in Wonderland was written by Lewis Carroll." },
    { question: "Какой самый старый город в мире?", answer: "Jericho is considered one of the oldest cities in the world." }
];
